### ISSUE TITLE
knnpred

### ISSUE THREAD

**Issue by kdemon1011** [ahmdtaha/TextureClassification_FilterBank#1]
knnpred is not a defined function.

I am getting this error while predicting the accuracy for the test classes.
Thank you

**Comment by ahmdtaha** [comment]
knnpred is a function inside the Classification toolbox for MATLAB, by Milano Chemometrics and QSAR Research Group. You need this toolbox to be able to use my code. For copyright issues, I didn't include it directly in my code but I shared a link for it inside the repos readme file.

Thanks
